/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.dk.me.logger.LoggerDriver;
import org.junit.Test;

public class LoggerDriverTest {
    @Test public void testSomeLibraryMethod() {
        LoggerDriver classUnderTest = new LoggerDriver();
//        assertEquals(5, classUnderTest.(5));
//        assertEquals(3, classUnderTest.fibonacci(4));
//        assertEquals(2, classUnderTest.fibonacci(3));
    }
}
